import { RootProvider } from "fumadocs-ui/provider";
import type { Metadata } from "next";

import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/icon-black.svg" />
      </head>
      <body className={"min-h-screen"}>
        <Toaster theme="light" richColors position={"top-center"} />
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
